/**
 * Turns the cached data/ files into the TypeScript the app imports. Runs at the end of
 * `pnpm sync`, or on its own with `pnpm generate` after editing the cache.
 *
 * Output is split deliberately: the index ships to the browser with every list and search,
 * the detail map is server-only. See src/lib/game-detail.ts.
 */
import { writeFile } from "node:fs/promises";
import path from "node:path";

import { loadData, readSource, ROOT } from "./lib/store.mjs";

const INDEX_FILE = path.join(ROOT, "src/lib/igdb.generated.ts");
const DETAIL_FILE = path.join(ROOT, "src/lib/igdb-detail.generated.ts");

const GB = 1024 ** 3;
const toGb = (bytes) => (bytes ? Math.round((bytes / GB) * 10) / 10 : null);

/** Xbox reports console generations as ConsoleGen8/9; the UI wants console names. */
const GEN_LABEL = { ConsoleGen8: "Xbox One", ConsoleGen9: "Xbox Series X|S" };

function xboxOf(record) {
  if (!record) return null;
  return {
    productId: record.productId,
    url: record.url,
    price: record.price,
    msrp: record.msrp,
    onSale: record.onSale,
    currency: record.currency,
    sizeGb: toGb(record.installBytes ?? record.downloadBytes),
    editions: record.editions,
    optimizedFor: (record.optimizedFor ?? []).map((g) => GEN_LABEL[g] ?? g),
    compatibleWith: (record.compatibleWith ?? []).map((g) => GEN_LABEL[g] ?? g),
    capabilities: record.capabilities ?? [],
  };
}

function nintendoOf(record) {
  if (!record) return null;
  const biggest = (record.romSizes ?? []).reduce((max, s) => (s.bytes > (max?.bytes ?? 0) ? s : max), null);
  return {
    nsuid: record.nsuid,
    url: record.url,
    price: record.price,
    regularPrice: record.regularPrice,
    discounted: Boolean(record.discounted),
    currency: record.currency ?? "USD",
    sizeGb: toGb(biggest?.bytes),
    platforms: record.platforms?.length ? record.platforms : record.platform ? [record.platform] : [],
    compatibility: record.compatibility?.caption ?? null,
    editions: record.editions ?? [],
  };
}

function playstationOf(record) {
  if (!record) return null;
  return {
    productId: record.productId,
    conceptId: record.conceptId,
    url: record.url,
    // Sony serves price and size only through a whitelisted GraphQL call; see the adapter.
    price: record.price,
    sizeGb: record.downloadBytes ? toGb(record.downloadBytes) : null,
  };
}

function render(header, imports, body) {
  return `${header}${imports}\n\n${body}\n`;
}

export async function generate() {
  const igdb = await readSource("igdb");
  const records = Object.values(igdb.entries).map((e) => e.data).filter(Boolean);
  if (records.length === 0) throw new Error("data/igdb.json is empty — run `pnpm sync` first");

  const [xbox, gamePass, nintendo, playstation, hltb] = await Promise.all([
    loadData("xboxStore"),
    loadData("gamePass"),
    loadData("nintendoStore"),
    loadData("playstationStore"),
    loadData("howLongToBeat"),
  ]);

  const date = new Date().toISOString().slice(0, 10);
  const sources = [
    `IGDB ${records.length}`,
    `Xbox ${xbox.size}`,
    `Game Pass ${gamePass.size}`,
    `Nintendo ${nintendo.size}`,
    `PlayStation ${playstation.size}`,
    `HLTB ${hltb.size}`,
  ].join(" · ");

  const head = (note) =>
    `// GENERATED by \`pnpm sync\` on ${date} — do not edit by hand.\n` +
    `// ${sources}\n// ${note}\n`;

  const index = [];
  const detail = [];

  for (const record of records.sort((a, b) => b.index.popularity - a.index.popularity)) {
    const id = record.index.igdbId;
    const pass = gamePass.get(id);
    index.push({ ...record.index, gamePass: pass ? (pass.console ? "console" : "pc") : null });

    const store = {
      xbox: xboxOf(xbox.get(id)),
      nintendo: nintendoOf(nintendo.get(id)),
      playstation: playstationOf(playstation.get(id)),
      gamePassTiers: pass ?? null,
      playtime: hltb.get(id) ?? null,
    };
    detail.push([record.index.slug, { ...record.detail, ...store }]);
  }

  await writeFile(
    INDEX_FILE,
    render(
      head("List index — shipped to the browser. Frame rates live in ./frame-data.ts."),
      'import type { IgdbGame } from "./types";\n\nexport const DATA_SYNCED_AT = "' + date + '";',
      `export const IGDB_GAMES: IgdbGame[] = [\n${index
        .map((r) => JSON.stringify(r, null, 2).split("\n").map((l) => `  ${l}`).join("\n"))
        .join(",\n")},\n];`,
    ),
  );

  await writeFile(
    DETAIL_FILE,
    render(
      head("Long-form fields and storefront data. Import from server components only."),
      'import type { GameDetailData } from "./types";',
      `export const IGDB_DETAILS: Record<string, GameDetailData> = {\n${detail
        .map(([slug, value]) => `  ${JSON.stringify(slug)}: ${JSON.stringify(value)}`)
        .join(",\n")},\n};`,
    ),
  );

  console.log(`  wrote ${index.length} titles — ${sources}`);
}

// Allow `node scripts/generate.mjs` on its own.
if (import.meta.url === `file://${process.argv[1]}`) await generate();
